// <auto-generated />
using System;
using CFKA.Health.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFKA.Health.Infrastructure.Migrations
{
    [DbContext(typeof(CFKATrainDbContext))]
    [Migration("20230906114200_UserRelatedTrain")]
    partial class UserRelatedTrain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuscleId")
                        .HasColumnType("integer");

                    b.Property<string>("PtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnName = "Incline Bench Press",
                            MuscleId = 1,
                            PtName = "Supino inclinado"
                        },
                        new
                        {
                            Id = 2,
                            EnName = "Incline Bench Press with Dumbbells",
                            MuscleId = 1,
                            PtName = "Supino inclinado com halteres"
                        },
                        new
                        {
                            Id = 3,
                            EnName = "Low Pulley Crossover",
                            MuscleId = 1,
                            PtName = "Crucifixo na polia baixa"
                        },
                        new
                        {
                            Id = 4,
                            EnName = "Incline Dumbbell Flyes",
                            MuscleId = 1,
                            PtName = "Crucifixo inclinado com halteres"
                        },
                        new
                        {
                            Id = 5,
                            EnName = "Incline Push-Ups",
                            MuscleId = 1,
                            PtName = "Flexao inclinado"
                        },
                        new
                        {
                            Id = 6,
                            EnName = "Bench Press",
                            MuscleId = 2,
                            PtName = "Supino reto"
                        },
                        new
                        {
                            Id = 7,
                            EnName = "Bench Press with Dumbbells",
                            MuscleId = 2,
                            PtName = "Supino reto com halteres"
                        },
                        new
                        {
                            Id = 8,
                            EnName = "Pulley Crossover",
                            MuscleId = 2,
                            PtName = "Crucifixo na polia reto"
                        },
                        new
                        {
                            Id = 9,
                            EnName = "Machine Crossover",
                            MuscleId = 2,
                            PtName = "Crucifixo na maquina"
                        },
                        new
                        {
                            Id = 10,
                            EnName = "Push-Up",
                            MuscleId = 2,
                            PtName = "Flexao"
                        },
                        new
                        {
                            Id = 11,
                            EnName = "Dumbbell Bench Press",
                            MuscleId = 2,
                            PtName = "Supino reto com halteres"
                        },
                        new
                        {
                            Id = 12,
                            EnName = "Chest Press Machine",
                            MuscleId = 2,
                            PtName = "Supino reto na maquina"
                        },
                        new
                        {
                            Id = 13,
                            EnName = "Dips",
                            MuscleId = 2,
                            PtName = "Mergulho"
                        },
                        new
                        {
                            Id = 14,
                            EnName = "Cable Chest Press",
                            MuscleId = 2,
                            PtName = "Supino com cabo"
                        },
                        new
                        {
                            Id = 15,
                            EnName = "Decline Bench Press",
                            MuscleId = 3,
                            PtName = "Supino declinado"
                        },
                        new
                        {
                            Id = 16,
                            EnName = "Decline Bench Press with Dumbbells",
                            MuscleId = 3,
                            PtName = "Supino declinado com halteres"
                        },
                        new
                        {
                            Id = 17,
                            EnName = "High Pulley Crossover",
                            MuscleId = 3,
                            PtName = "Crucifixo na polia alta"
                        },
                        new
                        {
                            Id = 18,
                            EnName = "Decline Dumbbell Flyes",
                            MuscleId = 3,
                            PtName = "Crucifixo declinado com halteres"
                        },
                        new
                        {
                            Id = 19,
                            EnName = "Decline Push-Ups",
                            MuscleId = 3,
                            PtName = "Flexao declinado"
                        },
                        new
                        {
                            Id = 20,
                            EnName = "Barbell high row",
                            MuscleId = 4,
                            PtName = "Remada alta com barra"
                        },
                        new
                        {
                            Id = 21,
                            EnName = "Dumbbells high row",
                            MuscleId = 4,
                            PtName = "Remada alta com halteres"
                        },
                        new
                        {
                            Id = 22,
                            EnName = "Shoulder shrugs",
                            MuscleId = 4,
                            PtName = "Encolhimento de ombros"
                        },
                        new
                        {
                            Id = 23,
                            EnName = "Trapeze raises",
                            MuscleId = 4,
                            PtName = "Elevação de trapézio"
                        },
                        new
                        {
                            Id = 24,
                            EnName = "Face pulls",
                            MuscleId = 4,
                            PtName = "Puxada de rosto"
                        },
                        new
                        {
                            Id = 25,
                            EnName = "Upright rows",
                            MuscleId = 4,
                            PtName = "Elevação frontal"
                        },
                        new
                        {
                            Id = 26,
                            EnName = "Power cleans",
                            MuscleId = 4,
                            PtName = "Arranco"
                        },
                        new
                        {
                            Id = 27,
                            EnName = "T-bar rows",
                            MuscleId = 4,
                            PtName = "Remada cavalinho"
                        },
                        new
                        {
                            Id = 28,
                            EnName = "Pull-ups",
                            MuscleId = 4,
                            PtName = "Barra fixa"
                        },
                        new
                        {
                            Id = 29,
                            EnName = "Lat pulldowns",
                            MuscleId = 4,
                            PtName = "Puxada alta"
                        },
                        new
                        {
                            Id = 30,
                            EnName = "Dumbbell Shrugs",
                            MuscleId = 4,
                            PtName = "Encolhimento de ombros com halteres"
                        },
                        new
                        {
                            Id = 31,
                            EnName = "Bent-Over Lateral Raises",
                            MuscleId = 4,
                            PtName = "Elevação lateral inclinado"
                        },
                        new
                        {
                            Id = 32,
                            EnName = "Kettlebell Swings",
                            MuscleId = 4,
                            PtName = "Balanço de kettlebell"
                        },
                        new
                        {
                            Id = 33,
                            EnName = "Arnold Press",
                            MuscleId = 4,
                            PtName = "Arnold Press"
                        },
                        new
                        {
                            Id = 34,
                            EnName = "Prone Y Raises",
                            MuscleId = 4,
                            PtName = "Elevação de Y pronada"
                        },
                        new
                        {
                            Id = 35,
                            EnName = "Front Pulley",
                            MuscleId = 5,
                            PtName = "Pulley frontal"
                        },
                        new
                        {
                            Id = 36,
                            EnName = "Back Pulley",
                            MuscleId = 5,
                            PtName = "Pulley traseiro"
                        },
                        new
                        {
                            Id = 37,
                            EnName = "Bent-over row",
                            MuscleId = 5,
                            PtName = "Remada curvada"
                        },
                        new
                        {
                            Id = 38,
                            EnName = "Pull-ups",
                            MuscleId = 5,
                            PtName = "Barra fixa"
                        },
                        new
                        {
                            Id = 39,
                            EnName = "Lat pulldowns",
                            MuscleId = 5,
                            PtName = "Puxada alta"
                        },
                        new
                        {
                            Id = 40,
                            EnName = "Seated cable rows",
                            MuscleId = 5,
                            PtName = "Remada sentada com cabo"
                        },
                        new
                        {
                            Id = 41,
                            EnName = "Wide grip pull-ups",
                            MuscleId = 5,
                            PtName = "Barra fixa com pegada ampla"
                        },
                        new
                        {
                            Id = 42,
                            EnName = "Inverted rows",
                            MuscleId = 5,
                            PtName = "Remada invertida"
                        },
                        new
                        {
                            Id = 43,
                            EnName = "Straight arm pulldowns",
                            MuscleId = 5,
                            PtName = "Puxada alta com braços estendidos"
                        },
                        new
                        {
                            Id = 44,
                            EnName = "Single-arm dumbbell rows",
                            MuscleId = 5,
                            PtName = "Remada unilateral com halteres"
                        },
                        new
                        {
                            Id = 45,
                            EnName = "Barbell Rows",
                            MuscleId = 5,
                            PtName = "Remada com barra"
                        },
                        new
                        {
                            Id = 46,
                            EnName = "Close-grip Pulldowns",
                            MuscleId = 5,
                            PtName = "Puxada alta com pegada fechada"
                        },
                        new
                        {
                            Id = 47,
                            EnName = "Underhand Cable Pulldowns",
                            MuscleId = 5,
                            PtName = "Puxada alta com pegada invertida"
                        },
                        new
                        {
                            Id = 48,
                            EnName = "Seated Row Machine",
                            MuscleId = 5,
                            PtName = "Remada sentada na máquina"
                        },
                        new
                        {
                            Id = 49,
                            EnName = "Wide Grip Cable Rows",
                            MuscleId = 5,
                            PtName = "Remada com cabo e pegada ampla"
                        },
                        new
                        {
                            Id = 50,
                            EnName = "Hyperextensions",
                            MuscleId = 6,
                            PtName = "Hiperextensões"
                        },
                        new
                        {
                            Id = 51,
                            EnName = "Deadlifts",
                            MuscleId = 6,
                            PtName = "Levantamento terra"
                        },
                        new
                        {
                            Id = 52,
                            EnName = "Good mornings",
                            MuscleId = 6,
                            PtName = "Bom dia"
                        },
                        new
                        {
                            Id = 53,
                            EnName = "Supermans",
                            MuscleId = 6,
                            PtName = "Super-homens"
                        },
                        new
                        {
                            Id = 54,
                            EnName = "Back extensions",
                            MuscleId = 6,
                            PtName = "Extensões de costas"
                        },
                        new
                        {
                            Id = 55,
                            EnName = "Romanian deadlifts",
                            MuscleId = 6,
                            PtName = "Levantamento terra romeno"
                        },
                        new
                        {
                            Id = 56,
                            EnName = "Reverse hypers",
                            MuscleId = 6,
                            PtName = "Hiperextensões reversas"
                        },
                        new
                        {
                            Id = 57,
                            EnName = "Bird dogs",
                            MuscleId = 6,
                            PtName = "Cachorros de caça"
                        },
                        new
                        {
                            Id = 58,
                            EnName = "Russian twists",
                            MuscleId = 6,
                            PtName = "Torções russas"
                        },
                        new
                        {
                            Id = 59,
                            EnName = "Plank variations",
                            MuscleId = 6,
                            PtName = "Variações de prancha"
                        },
                        new
                        {
                            Id = 60,
                            EnName = "Seated Good Mornings",
                            MuscleId = 6,
                            PtName = "Bom dia sentado"
                        },
                        new
                        {
                            Id = 61,
                            EnName = "Prone Back Extensions",
                            MuscleId = 6,
                            PtName = "Extensões de costas prono"
                        },
                        new
                        {
                            Id = 62,
                            EnName = "Seated Cable Hyperextensions",
                            MuscleId = 6,
                            PtName = "Hiperextensões com cabo sentado"
                        },
                        new
                        {
                            Id = 63,
                            EnName = "Kettlebell Swings",
                            MuscleId = 6,
                            PtName = "Balanços com kettlebell"
                        },
                        new
                        {
                            Id = 64,
                            EnName = "Reverse Hyper Machine",
                            MuscleId = 6,
                            PtName = "Máquina de hiperextensões reversas"
                        },
                        new
                        {
                            Id = 65,
                            EnName = "Barbell curls",
                            MuscleId = 7,
                            PtName = "Rosca direta com barra"
                        },
                        new
                        {
                            Id = 66,
                            EnName = "Dumbbell Hammer curls",
                            MuscleId = 7,
                            PtName = "Rosca martelo com halteres"
                        },
                        new
                        {
                            Id = 67,
                            EnName = "Preacher Hammer curls",
                            MuscleId = 7,
                            PtName = "Rosca martelo no banco scott"
                        },
                        new
                        {
                            Id = 68,
                            EnName = "Cable Hammer curls",
                            MuscleId = 7,
                            PtName = "Rosca martelo com cabo"
                        },
                        new
                        {
                            Id = 69,
                            EnName = "Incline Hammer curls",
                            MuscleId = 7,
                            PtName = "Rosca martelo inclinada"
                        },
                        new
                        {
                            Id = 70,
                            EnName = "Hammer curls",
                            MuscleId = 8,
                            PtName = "Rosca martelo"
                        },
                        new
                        {
                            Id = 71,
                            EnName = "Reverse curls",
                            MuscleId = 8,
                            PtName = "Rosca inversa"
                        },
                        new
                        {
                            Id = 72,
                            EnName = "Wrist curls",
                            MuscleId = 8,
                            PtName = "Rosca de punho"
                        },
                        new
                        {
                            Id = 73,
                            EnName = "Zottman curls",
                            MuscleId = 8,
                            PtName = "Rosca Zottman"
                        },
                        new
                        {
                            Id = 74,
                            EnName = "EZ bar reverse curls",
                            MuscleId = 8,
                            PtName = "Rosca inversa com barra EZ"
                        },
                        new
                        {
                            Id = 75,
                            EnName = "Dumbbell curls",
                            MuscleId = 9,
                            PtName = "Rosca alternada com halteres"
                        },
                        new
                        {
                            Id = 76,
                            EnName = "Preacher curls",
                            MuscleId = 9,
                            PtName = "Rosca no banco scott"
                        },
                        new
                        {
                            Id = 77,
                            EnName = "Concentration curls",
                            MuscleId = 9,
                            PtName = "Rosca concentrada"
                        },
                        new
                        {
                            Id = 78,
                            EnName = "EZ bar curls",
                            MuscleId = 9,
                            PtName = "Rosca direta com barra EZ"
                        },
                        new
                        {
                            Id = 79,
                            EnName = "Incline dumbbell curls",
                            MuscleId = 9,
                            PtName = "Rosca inclinada com halteres"
                        },
                        new
                        {
                            Id = 80,
                            EnName = "Cable curls",
                            MuscleId = 9,
                            PtName = "Rosca com cabo"
                        },
                        new
                        {
                            Id = 81,
                            EnName = "Spider curls",
                            MuscleId = 9,
                            PtName = "Rosca aranha"
                        },
                        new
                        {
                            Id = 82,
                            EnName = "Chin-ups",
                            MuscleId = 9,
                            PtName = "Barra fixa"
                        },
                        new
                        {
                            Id = 83,
                            EnName = "Seated Dumbbell curls",
                            MuscleId = 9,
                            PtName = "Rosca alternada sentado"
                        },
                        new
                        {
                            Id = 84,
                            EnName = "Hammer Strength curls",
                            MuscleId = 9,
                            PtName = "Rosca Hammer Strength"
                        },
                        new
                        {
                            Id = 85,
                            EnName = "Machine curls",
                            MuscleId = 9,
                            PtName = "Rosca na máquina"
                        },
                        new
                        {
                            Id = 86,
                            EnName = "Close-grip Chin-ups",
                            MuscleId = 9,
                            PtName = "Barra fixa pegada fechada"
                        },
                        new
                        {
                            Id = 87,
                            EnName = "Preacher Hammer curls",
                            MuscleId = 9,
                            PtName = "Rosca martelo no banco scott"
                        },
                        new
                        {
                            Id = 88,
                            EnName = "Close grip bench press",
                            MuscleId = 10,
                            PtName = "Supino pegada fechada"
                        },
                        new
                        {
                            Id = 89,
                            EnName = "Dips",
                            MuscleId = 10,
                            PtName = "Paralelas"
                        },
                        new
                        {
                            Id = 90,
                            EnName = "Diamond push-ups",
                            MuscleId = 10,
                            PtName = "Flexão diamante"
                        },
                        new
                        {
                            Id = 91,
                            EnName = "Overhead dumbbell extension",
                            MuscleId = 10,
                            PtName = "Extensão de tríceps com halter acima da cabeça"
                        },
                        new
                        {
                            Id = 92,
                            EnName = "Reverse grip triceps pushdown",
                            MuscleId = 10,
                            PtName = "Tríceps pulldown com pegada invertida"
                        },
                        new
                        {
                            Id = 93,
                            EnName = "Triceps pushdown",
                            MuscleId = 11,
                            PtName = "Tríceps pulldown"
                        },
                        new
                        {
                            Id = 94,
                            EnName = "Triceps kickbacks",
                            MuscleId = 11,
                            PtName = "Tríceps kickback"
                        },
                        new
                        {
                            Id = 95,
                            EnName = "Triceps rope pushdown",
                            MuscleId = 11,
                            PtName = "Tríceps pulldown com corda"
                        },
                        new
                        {
                            Id = 96,
                            EnName = "Close grip push-ups",
                            MuscleId = 11,
                            PtName = "Flexão de braço pegada fechada"
                        },
                        new
                        {
                            Id = 97,
                            EnName = "Bench dips",
                            MuscleId = 11,
                            PtName = "Mergulho de banco"
                        },
                        new
                        {
                            Id = 98,
                            EnName = "Overhead triceps extension",
                            MuscleId = 12,
                            PtName = "Extensão de tríceps acima da cabeça"
                        },
                        new
                        {
                            Id = 99,
                            EnName = "Skull crushers",
                            MuscleId = 12,
                            PtName = "Crucifixo invertido"
                        },
                        new
                        {
                            Id = 100,
                            EnName = "Bench dips",
                            MuscleId = 12,
                            PtName = "Mergulho de banco"
                        },
                        new
                        {
                            Id = 101,
                            EnName = "Overhead cable triceps extension",
                            MuscleId = 12,
                            PtName = "Extensão de tríceps com cabo acima da cabeça"
                        },
                        new
                        {
                            Id = 102,
                            EnName = "Dumbbell triceps kickbacks",
                            MuscleId = 12,
                            PtName = "Tríceps kickback com halteres"
                        },
                        new
                        {
                            Id = 103,
                            EnName = "Crunches",
                            MuscleId = 13,
                            PtName = "Abdominais"
                        },
                        new
                        {
                            Id = 104,
                            EnName = "Plank",
                            MuscleId = 13,
                            PtName = "Prancha"
                        },
                        new
                        {
                            Id = 105,
                            EnName = "Sit-ups",
                            MuscleId = 13,
                            PtName = "Flexões de tronco"
                        },
                        new
                        {
                            Id = 106,
                            EnName = "Mountain climbers",
                            MuscleId = 13,
                            PtName = "Montanhistas"
                        },
                        new
                        {
                            Id = 107,
                            EnName = "Ab wheel rollouts",
                            MuscleId = 13,
                            PtName = "Extensões de abdômen com roda"
                        },
                        new
                        {
                            Id = 108,
                            EnName = "Leg raises",
                            MuscleId = 14,
                            PtName = "Elevação de pernas"
                        },
                        new
                        {
                            Id = 109,
                            EnName = "Hanging knee raises",
                            MuscleId = 14,
                            PtName = "Elevação de joelhos suspensa"
                        },
                        new
                        {
                            Id = 110,
                            EnName = "Reverse crunches",
                            MuscleId = 14,
                            PtName = "Crunches invertidos"
                        },
                        new
                        {
                            Id = 111,
                            EnName = "Scissor kicks",
                            MuscleId = 14,
                            PtName = "Tesoura"
                        },
                        new
                        {
                            Id = 112,
                            EnName = "Captain's chair leg raises",
                            MuscleId = 14,
                            PtName = "Elevação de pernas na cadeira romana"
                        },
                        new
                        {
                            Id = 113,
                            EnName = "Russian twists",
                            MuscleId = 15,
                            PtName = "Torções russas"
                        },
                        new
                        {
                            Id = 114,
                            EnName = "Side plank",
                            MuscleId = 15,
                            PtName = "Prancha lateral"
                        },
                        new
                        {
                            Id = 115,
                            EnName = "Bicycle crunches",
                            MuscleId = 15,
                            PtName = "Abdominais de bicicleta"
                        },
                        new
                        {
                            Id = 116,
                            EnName = "Woodchoppers",
                            MuscleId = 15,
                            PtName = "Cortadores de lenha"
                        },
                        new
                        {
                            Id = 117,
                            EnName = "Standing oblique crunches",
                            MuscleId = 15,
                            PtName = "Abdominais oblíquos em pé"
                        },
                        new
                        {
                            Id = 118,
                            EnName = "Standing calf raises",
                            MuscleId = 16,
                            PtName = "Elevação de panturrilha em pé"
                        },
                        new
                        {
                            Id = 119,
                            EnName = "Donkey calf raises",
                            MuscleId = 16,
                            PtName = "Elevação de panturrilha no aparelho burro"
                        },
                        new
                        {
                            Id = 120,
                            EnName = "Calf press on leg press machine",
                            MuscleId = 16,
                            PtName = "Pressão de panturrilha no aparelho de leg press"
                        },
                        new
                        {
                            Id = 121,
                            EnName = "Skipping rope",
                            MuscleId = 16,
                            PtName = "Pular corda"
                        },
                        new
                        {
                            Id = 122,
                            EnName = "Jump rope calf jumps",
                            MuscleId = 16,
                            PtName = "Saltos de panturrilha com corda"
                        },
                        new
                        {
                            Id = 123,
                            EnName = "Seated calf raises",
                            MuscleId = 17,
                            PtName = "Elevação de panturrilha sentado"
                        },
                        new
                        {
                            Id = 124,
                            EnName = "Single-leg calf raises",
                            MuscleId = 17,
                            PtName = "Elevação de panturrilha em uma perna"
                        },
                        new
                        {
                            Id = 125,
                            EnName = "Calf raises on a step",
                            MuscleId = 17,
                            PtName = "Elevação de panturrilha em um degrau"
                        },
                        new
                        {
                            Id = 126,
                            EnName = "Sled pushes",
                            MuscleId = 17,
                            PtName = "Empurrões com trenó"
                        },
                        new
                        {
                            Id = 127,
                            EnName = "Calf raises with resistance bands",
                            MuscleId = 17,
                            PtName = "Elevação de panturrilha com faixas de resistência"
                        },
                        new
                        {
                            Id = 128,
                            EnName = "Toe raises",
                            MuscleId = 18,
                            PtName = "Elevação de ponta de pé"
                        },
                        new
                        {
                            Id = 129,
                            EnName = "Box jumps",
                            MuscleId = 18,
                            PtName = "Saltos em caixa"
                        },
                        new
                        {
                            Id = 130,
                            EnName = "Ankle dorsiflexion with resistance band",
                            MuscleId = 18,
                            PtName = "Dorsiflexão de tornozelo com faixa de resistência"
                        },
                        new
                        {
                            Id = 131,
                            EnName = "Treadmill incline walks",
                            MuscleId = 18,
                            PtName = "Caminhadas em esteira inclinada"
                        },
                        new
                        {
                            Id = 132,
                            EnName = "Squats",
                            MuscleId = 19,
                            PtName = "Agachamentos"
                        },
                        new
                        {
                            Id = 133,
                            EnName = "Step-ups",
                            MuscleId = 19,
                            PtName = "Elevação de perna"
                        },
                        new
                        {
                            Id = 134,
                            EnName = "Front squats",
                            MuscleId = 19,
                            PtName = "Agachamentos frontais"
                        },
                        new
                        {
                            Id = 135,
                            EnName = "Wall sits",
                            MuscleId = 19,
                            PtName = "Agachamento estático"
                        },
                        new
                        {
                            Id = 136,
                            EnName = "Leg press",
                            MuscleId = 19,
                            PtName = "Pressão de pernas"
                        },
                        new
                        {
                            Id = 137,
                            EnName = "Lunges",
                            MuscleId = 20,
                            PtName = "Avanço"
                        },
                        new
                        {
                            Id = 138,
                            EnName = "Hack squats",
                            MuscleId = 20,
                            PtName = "Agachamentos hack"
                        },
                        new
                        {
                            Id = 139,
                            EnName = "Leg extensions",
                            MuscleId = 20,
                            PtName = "Extensões de pernas"
                        },
                        new
                        {
                            Id = 140,
                            EnName = "Leg press",
                            MuscleId = 20,
                            PtName = "Pressão de pernas"
                        },
                        new
                        {
                            Id = 141,
                            EnName = "Leg press with feet high",
                            MuscleId = 20,
                            PtName = "Pressão de pernas com os pés elevados"
                        },
                        new
                        {
                            Id = 142,
                            EnName = "Leg press",
                            MuscleId = 21,
                            PtName = "Pressão de pernas"
                        },
                        new
                        {
                            Id = 143,
                            EnName = "Bulgarian split squats",
                            MuscleId = 21,
                            PtName = "Agachamentos búlgaros"
                        },
                        new
                        {
                            Id = 144,
                            EnName = "Pistol squats",
                            MuscleId = 21,
                            PtName = "Agachamentos pistol"
                        },
                        new
                        {
                            Id = 145,
                            EnName = "Lunges",
                            MuscleId = 21,
                            PtName = "Avanço"
                        },
                        new
                        {
                            Id = 146,
                            EnName = "Leg extensions",
                            MuscleId = 21,
                            PtName = "Extensões de pernas"
                        },
                        new
                        {
                            Id = 147,
                            EnName = "Hip thrusts",
                            MuscleId = 22,
                            PtName = "Levantamento de quadril"
                        },
                        new
                        {
                            Id = 148,
                            EnName = "Donkey kicks",
                            MuscleId = 22,
                            PtName = "Chutes de burro"
                        },
                        new
                        {
                            Id = 149,
                            EnName = "Sumo squats",
                            MuscleId = 22,
                            PtName = "Agachamentos sumo"
                        },
                        new
                        {
                            Id = 150,
                            EnName = "Kickbacks",
                            MuscleId = 22,
                            PtName = "Extensões de perna"
                        },
                        new
                        {
                            Id = 151,
                            EnName = "Bulgarian split squats",
                            MuscleId = 22,
                            PtName = "Agachamentos búlgaros"
                        },
                        new
                        {
                            Id = 152,
                            EnName = "Clamshell exercises",
                            MuscleId = 23,
                            PtName = "Exercícios de conchinha"
                        },
                        new
                        {
                            Id = 153,
                            EnName = "Fire hydrants",
                            MuscleId = 23,
                            PtName = "Hidrantes"
                        },
                        new
                        {
                            Id = 154,
                            EnName = "Side-lying leg lifts",
                            MuscleId = 23,
                            PtName = "Elevações de perna deitado de lado"
                        },
                        new
                        {
                            Id = 155,
                            EnName = "Lateral band walks",
                            MuscleId = 23,
                            PtName = "Caminhadas laterais com banda"
                        },
                        new
                        {
                            Id = 156,
                            EnName = "Glute bridges",
                            MuscleId = 24,
                            PtName = "Ponte de glúteo"
                        },
                        new
                        {
                            Id = 157,
                            EnName = "Single-leg hip thrusts",
                            MuscleId = 24,
                            PtName = "Levantamento de quadril com uma perna"
                        },
                        new
                        {
                            Id = 158,
                            EnName = "Banded crab walks",
                            MuscleId = 24,
                            PtName = "Caminhadas de caranguejo com banda"
                        },
                        new
                        {
                            Id = 159,
                            EnName = "Reverse lunges",
                            MuscleId = 24,
                            PtName = "Avanço reverso"
                        },
                        new
                        {
                            Id = 160,
                            EnName = "Wrist curls",
                            MuscleId = 25,
                            PtName = "Flexões de pulso"
                        },
                        new
                        {
                            Id = 161,
                            EnName = "Plate curls",
                            MuscleId = 25,
                            PtName = "Cachos com placa"
                        },
                        new
                        {
                            Id = 162,
                            EnName = "Pinch grip holds",
                            MuscleId = 25,
                            PtName = "Agarre de pinça"
                        },
                        new
                        {
                            Id = 163,
                            EnName = "Finger curls",
                            MuscleId = 25,
                            PtName = "Cachos de dedos"
                        },
                        new
                        {
                            Id = 164,
                            EnName = "Dumbbell wrist pronation/supination",
                            MuscleId = 25,
                            PtName = "Pronação/supinação de pulso com halteres"
                        },
                        new
                        {
                            Id = 165,
                            EnName = "Reverse wrist curls",
                            MuscleId = 26,
                            PtName = "Flexões reversas de pulso"
                        },
                        new
                        {
                            Id = 166,
                            EnName = "Hammer grip curls",
                            MuscleId = 26,
                            PtName = "Cachos com pegada de martelo"
                        },
                        new
                        {
                            Id = 167,
                            EnName = "Bar hangs",
                            MuscleId = 26,
                            PtName = "Pendurar na barra"
                        },
                        new
                        {
                            Id = 168,
                            EnName = "Wrist roller",
                            MuscleId = 26,
                            PtName = "Rolo de pulso"
                        },
                        new
                        {
                            Id = 169,
                            EnName = "Grip strengthener exercises",
                            MuscleId = 27,
                            PtName = "Exercícios para fortalecer o agarre"
                        },
                        new
                        {
                            Id = 170,
                            EnName = "Towel hangs",
                            MuscleId = 27,
                            PtName = "Pendurar com toalha"
                        },
                        new
                        {
                            Id = 171,
                            EnName = "Farmer's walks",
                            MuscleId = 27,
                            PtName = "Caminhadas de fazendeiro"
                        },
                        new
                        {
                            Id = 172,
                            EnName = "Plate pinches",
                            MuscleId = 27,
                            PtName = "Apertar de pratos"
                        },
                        new
                        {
                            Id = 173,
                            EnName = "Military Press",
                            MuscleId = 28,
                            PtName = "Desenvolvimento Militar"
                        },
                        new
                        {
                            Id = 174,
                            EnName = "Arnold Press",
                            MuscleId = 28,
                            PtName = "Arnold Press"
                        },
                        new
                        {
                            Id = 175,
                            EnName = "Front Dumbbell Raise",
                            MuscleId = 28,
                            PtName = "Elevação frontal com halteres"
                        },
                        new
                        {
                            Id = 176,
                            EnName = "Barbell Front Raise",
                            MuscleId = 28,
                            PtName = "Elevação frontal com barra"
                        },
                        new
                        {
                            Id = 177,
                            EnName = "Cable Front Raise",
                            MuscleId = 28,
                            PtName = "Elevação frontal com cabo"
                        },
                        new
                        {
                            Id = 178,
                            EnName = "Lateral Raises",
                            MuscleId = 29,
                            PtName = "Elevação lateral"
                        },
                        new
                        {
                            Id = 179,
                            EnName = "Dumbbell Lateral Raises",
                            MuscleId = 29,
                            PtName = "Elevação lateral com halteres"
                        },
                        new
                        {
                            Id = 180,
                            EnName = "Cable Lateral Raises",
                            MuscleId = 29,
                            PtName = "Elevação lateral com cabo"
                        },
                        new
                        {
                            Id = 181,
                            EnName = "Machine Lateral Raises",
                            MuscleId = 29,
                            PtName = "Elevação lateral na máquina"
                        },
                        new
                        {
                            Id = 182,
                            EnName = "Bent-Over Lateral Raises",
                            MuscleId = 29,
                            PtName = "Elevação lateral inclinada"
                        },
                        new
                        {
                            Id = 183,
                            EnName = "Rear Deltoid Flyes",
                            MuscleId = 30,
                            PtName = "Flyes para deltoides posteriores"
                        },
                        new
                        {
                            Id = 184,
                            EnName = "Bent-Over Rear Deltoid Raises",
                            MuscleId = 30,
                            PtName = "Elevação de deltoides posteriores inclinado"
                        },
                        new
                        {
                            Id = 185,
                            EnName = "Cable Rear Deltoid Flyes",
                            MuscleId = 30,
                            PtName = "Flyes para deltoides posteriores com cabo"
                        },
                        new
                        {
                            Id = 186,
                            EnName = "Reverse Pec Deck Flyes",
                            MuscleId = 30,
                            PtName = "Flyes inversos no peck deck"
                        },
                        new
                        {
                            Id = 187,
                            EnName = "Face Pulls",
                            MuscleId = 30,
                            PtName = "Face Pulls"
                        });
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MainMuscle")
                        .HasColumnType("integer");

                    b.Property<string>("PtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnName = "Upper Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Superior"
                        },
                        new
                        {
                            Id = 2,
                            EnName = "Middle Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Medio"
                        },
                        new
                        {
                            Id = 3,
                            EnName = "Lower Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Inferior"
                        },
                        new
                        {
                            Id = 4,
                            EnName = "Trapezius",
                            MainMuscle = 1,
                            PtName = "Trapezio"
                        },
                        new
                        {
                            Id = 5,
                            EnName = "Lats",
                            MainMuscle = 1,
                            PtName = "Dorsal"
                        },
                        new
                        {
                            Id = 6,
                            EnName = "Low Back",
                            MainMuscle = 1,
                            PtName = "Lombar"
                        },
                        new
                        {
                            Id = 7,
                            EnName = "Brachialis",
                            MainMuscle = 3,
                            PtName = "Braquial"
                        },
                        new
                        {
                            Id = 8,
                            EnName = "Brachioradialis",
                            MainMuscle = 3,
                            PtName = "Braquiorradial"
                        },
                        new
                        {
                            Id = 9,
                            EnName = "Biceps Brachii",
                            MainMuscle = 3,
                            PtName = "Biceps Braquial"
                        },
                        new
                        {
                            Id = 10,
                            EnName = "Long Head of Triceps",
                            MainMuscle = 4,
                            PtName = "Cabeça Longa do Triceps"
                        },
                        new
                        {
                            Id = 11,
                            EnName = "Medial Head of Triceps",
                            MainMuscle = 4,
                            PtName = "Cabeça Media do Triceps"
                        },
                        new
                        {
                            Id = 12,
                            EnName = "Lateral Head of Triceps",
                            MainMuscle = 4,
                            PtName = "Cabeça Lateral do Triceps"
                        },
                        new
                        {
                            Id = 13,
                            EnName = "Upper Abs",
                            MainMuscle = 5,
                            PtName = "Abdominais Superiores"
                        },
                        new
                        {
                            Id = 14,
                            EnName = "Lower Abs",
                            MainMuscle = 5,
                            PtName = "Abdominais Inferiores"
                        },
                        new
                        {
                            Id = 15,
                            EnName = "Obliques",
                            MainMuscle = 5,
                            PtName = "Oblíquos"
                        },
                        new
                        {
                            Id = 16,
                            EnName = "Gastrocnemius (Upper Calf)",
                            MainMuscle = 6,
                            PtName = "Gastrocnêmio (Parte superior da panturrilha)"
                        },
                        new
                        {
                            Id = 17,
                            EnName = "Soleus (Lower Calf)",
                            MainMuscle = 6,
                            PtName = "Sóleo (Parte inferior da panturrilha)"
                        },
                        new
                        {
                            Id = 18,
                            EnName = "Tibialis Anterior",
                            MainMuscle = 6,
                            PtName = "Tibial Anterior"
                        },
                        new
                        {
                            Id = 19,
                            EnName = "Vastus Lateralis",
                            MainMuscle = 7,
                            PtName = "Vasto lateral"
                        },
                        new
                        {
                            Id = 20,
                            EnName = "Vastus Medialis",
                            MainMuscle = 7,
                            PtName = "Vasto Medial"
                        },
                        new
                        {
                            Id = 21,
                            EnName = "Rectus Femoris",
                            MainMuscle = 7,
                            PtName = "Reto Femoral"
                        },
                        new
                        {
                            Id = 22,
                            EnName = "Gluteus Maximus",
                            MainMuscle = 8,
                            PtName = "Gluteo Maximo"
                        },
                        new
                        {
                            Id = 23,
                            EnName = "Gluteus Medius",
                            MainMuscle = 8,
                            PtName = "Gluteo Medio"
                        },
                        new
                        {
                            Id = 24,
                            EnName = "Gluteus Minimus",
                            MainMuscle = 8,
                            PtName = "Gluteo Minimo"
                        },
                        new
                        {
                            Id = 25,
                            EnName = "Wrist Flexors",
                            MainMuscle = 9,
                            PtName = "Flexores de Punho"
                        },
                        new
                        {
                            Id = 26,
                            EnName = "Wrist Extensors",
                            MainMuscle = 9,
                            PtName = "Extensores de Punho"
                        },
                        new
                        {
                            Id = 27,
                            EnName = "Grip",
                            MainMuscle = 9,
                            PtName = "Pegada"
                        },
                        new
                        {
                            Id = 28,
                            EnName = "Front Deltoids",
                            MainMuscle = 2,
                            PtName = "Deltoides Frontais"
                        },
                        new
                        {
                            Id = 29,
                            EnName = "Side Deltoids",
                            MainMuscle = 2,
                            PtName = "Deltoides Laterais"
                        },
                        new
                        {
                            Id = 30,
                            EnName = "Rear Deltoids",
                            MainMuscle = 2,
                            PtName = "Deltoides Posteriores"
                        });
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.TrainingExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExercises");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("CFKA.Health.Domain.Entities.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Training", b =>
                {
                    b.HasOne("CFKA.Health.Domain.Entities.User", "Owner")
                        .WithMany("Trainings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.TrainingExercise", b =>
                {
                    b.HasOne("CFKA.Health.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CFKA.Health.Domain.Entities.Training", "Training")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Training", b =>
                {
                    b.Navigation("TrainingExercises");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.User", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
