// <auto-generated />
using CFKA.Health.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFKA.Health.Infrastructure.Migrations
{
    [DbContext(typeof(CFKATrainDbContext))]
    [Migration("20230601184426_ptBr_Translation_muscles")]
    partial class ptBr_Translation_muscles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuscleId")
                        .HasColumnType("integer");

                    b.Property<string>("PtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MainMuscle")
                        .HasColumnType("integer");

                    b.Property<string>("PtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnName = "Upper Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Superior"
                        },
                        new
                        {
                            Id = 2,
                            EnName = "Middle Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Medio"
                        },
                        new
                        {
                            Id = 3,
                            EnName = "Lower Chest",
                            MainMuscle = 0,
                            PtName = "Peitoral Inferior"
                        },
                        new
                        {
                            Id = 4,
                            EnName = "Trapezius",
                            MainMuscle = 1,
                            PtName = "Trapezio"
                        },
                        new
                        {
                            Id = 5,
                            EnName = "Lats",
                            MainMuscle = 1,
                            PtName = "Dorsal"
                        },
                        new
                        {
                            Id = 6,
                            EnName = "Low Back",
                            MainMuscle = 1,
                            PtName = "Lombar"
                        },
                        new
                        {
                            Id = 7,
                            EnName = "Brachialis",
                            MainMuscle = 2,
                            PtName = "Braquial"
                        },
                        new
                        {
                            Id = 8,
                            EnName = "Brachioradialis",
                            MainMuscle = 2,
                            PtName = "Braquiorradial"
                        },
                        new
                        {
                            Id = 9,
                            EnName = "Biceps Brachii",
                            MainMuscle = 2,
                            PtName = "Biceps Braquial"
                        },
                        new
                        {
                            Id = 10,
                            EnName = "Long Head of Triceps",
                            MainMuscle = 3,
                            PtName = "Cabeça Longa do Triceps"
                        },
                        new
                        {
                            Id = 11,
                            EnName = "Medial Head of Triceps",
                            MainMuscle = 3,
                            PtName = "Cabeça Media do Triceps"
                        },
                        new
                        {
                            Id = 12,
                            EnName = "Lateral Head of Triceps",
                            MainMuscle = 3,
                            PtName = "Cabeça Lateral do Triceps"
                        },
                        new
                        {
                            Id = 13,
                            EnName = "Upper Abs",
                            MainMuscle = 4,
                            PtName = "Abdominais Superiores"
                        },
                        new
                        {
                            Id = 14,
                            EnName = "Lower Abs",
                            MainMuscle = 4,
                            PtName = "Abdominais Inferiores"
                        },
                        new
                        {
                            Id = 15,
                            EnName = "Obliques",
                            MainMuscle = 4,
                            PtName = "Oblíquos"
                        },
                        new
                        {
                            Id = 16,
                            EnName = "Gastrocnemius (Upper Calf)",
                            MainMuscle = 5,
                            PtName = "Gastrocnêmio (Parte superior da panturrilha)"
                        },
                        new
                        {
                            Id = 17,
                            EnName = "Soleus (Lower Calf)",
                            MainMuscle = 5,
                            PtName = "Sóleo (Parte inferior da panturrilha)"
                        },
                        new
                        {
                            Id = 18,
                            EnName = "Tibialis Anterior",
                            MainMuscle = 5,
                            PtName = "Tibial Anterior"
                        },
                        new
                        {
                            Id = 19,
                            EnName = "Vastus Lateralis",
                            MainMuscle = 6,
                            PtName = "Vasto lateral"
                        },
                        new
                        {
                            Id = 20,
                            EnName = "Vastus Medialis",
                            MainMuscle = 6,
                            PtName = "Vasto Medial"
                        },
                        new
                        {
                            Id = 21,
                            EnName = "Rectus Femoris",
                            MainMuscle = 6,
                            PtName = "Reto Femoral"
                        },
                        new
                        {
                            Id = 22,
                            EnName = "Gluteus Maximus",
                            MainMuscle = 7,
                            PtName = "Gluteo Maximo"
                        },
                        new
                        {
                            Id = 23,
                            EnName = "Gluteus Medius",
                            MainMuscle = 7,
                            PtName = "Gluteo Medio"
                        },
                        new
                        {
                            Id = 24,
                            EnName = "Gluteus Minimus",
                            MainMuscle = 7,
                            PtName = "Gluteo Minimo"
                        },
                        new
                        {
                            Id = 25,
                            EnName = "Wrist Flexors",
                            MainMuscle = 8,
                            PtName = "Flexores de Punho"
                        },
                        new
                        {
                            Id = 26,
                            EnName = "Wrist Extensors",
                            MainMuscle = 8,
                            PtName = "Extensores de Punho"
                        },
                        new
                        {
                            Id = 27,
                            EnName = "Grip",
                            MainMuscle = 8,
                            PtName = "Pegada"
                        });
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("CFKA.Health.Domain.Entities.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });
#pragma warning restore 612, 618
        }
    }
}
