// <auto-generated />
using CFKA.Health.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFKA.Health.Infrastructure.Migrations
{
    [DbContext(typeof(CFKATrainDbContext))]
    partial class CFKATrainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MuscleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleId = 1,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            MuscleId = 1,
                            Name = "Incline Bench Press with Dumbbells"
                        },
                        new
                        {
                            Id = 3,
                            MuscleId = 1,
                            Name = "Low Pulley Crossover"
                        },
                        new
                        {
                            Id = 4,
                            MuscleId = 1,
                            Name = "Incline Dumbbell Flyes"
                        },
                        new
                        {
                            Id = 5,
                            MuscleId = 1,
                            Name = "Incline Push-Ups"
                        },
                        new
                        {
                            Id = 6,
                            MuscleId = 2,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 7,
                            MuscleId = 2,
                            Name = "Bench Press with Dumbbells"
                        },
                        new
                        {
                            Id = 8,
                            MuscleId = 2,
                            Name = "Pulley Crossover"
                        },
                        new
                        {
                            Id = 9,
                            MuscleId = 2,
                            Name = "Machine Crossover"
                        },
                        new
                        {
                            Id = 10,
                            MuscleId = 2,
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = 11,
                            MuscleId = 2,
                            Name = "Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 12,
                            MuscleId = 2,
                            Name = "Chest Press Machine"
                        },
                        new
                        {
                            Id = 13,
                            MuscleId = 2,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 14,
                            MuscleId = 2,
                            Name = "Cable Chest Press"
                        },
                        new
                        {
                            Id = 15,
                            MuscleId = 3,
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = 16,
                            MuscleId = 3,
                            Name = "Decline Bench Press with Dumbbells"
                        },
                        new
                        {
                            Id = 17,
                            MuscleId = 3,
                            Name = "High Pulley Crossover"
                        },
                        new
                        {
                            Id = 18,
                            MuscleId = 3,
                            Name = "Decline Dumbbell Flyes"
                        },
                        new
                        {
                            Id = 19,
                            MuscleId = 3,
                            Name = "Decline Push-Ups"
                        },
                        new
                        {
                            Id = 20,
                            MuscleId = 4,
                            Name = "Barbell high row"
                        },
                        new
                        {
                            Id = 21,
                            MuscleId = 4,
                            Name = "Dumbbells high row"
                        },
                        new
                        {
                            Id = 22,
                            MuscleId = 4,
                            Name = "Shoulder shrugs"
                        },
                        new
                        {
                            Id = 23,
                            MuscleId = 4,
                            Name = "Trapeze raises"
                        },
                        new
                        {
                            Id = 24,
                            MuscleId = 4,
                            Name = "Face pulls"
                        },
                        new
                        {
                            Id = 25,
                            MuscleId = 4,
                            Name = "Upright rows"
                        },
                        new
                        {
                            Id = 26,
                            MuscleId = 4,
                            Name = "Power cleans"
                        },
                        new
                        {
                            Id = 27,
                            MuscleId = 4,
                            Name = "T-bar rows"
                        },
                        new
                        {
                            Id = 28,
                            MuscleId = 4,
                            Name = "Pull-ups"
                        },
                        new
                        {
                            Id = 29,
                            MuscleId = 4,
                            Name = "Lat pulldowns"
                        },
                        new
                        {
                            Id = 30,
                            MuscleId = 4,
                            Name = "Dumbbell Shrugs"
                        },
                        new
                        {
                            Id = 31,
                            MuscleId = 4,
                            Name = "Bent-Over Lateral Raises"
                        },
                        new
                        {
                            Id = 32,
                            MuscleId = 4,
                            Name = "Kettlebell Swings"
                        },
                        new
                        {
                            Id = 33,
                            MuscleId = 4,
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 34,
                            MuscleId = 4,
                            Name = "Prone Y Raises"
                        },
                        new
                        {
                            Id = 35,
                            MuscleId = 5,
                            Name = "Front Pulley"
                        },
                        new
                        {
                            Id = 36,
                            MuscleId = 5,
                            Name = "Back Pulley"
                        },
                        new
                        {
                            Id = 37,
                            MuscleId = 5,
                            Name = "Bent-over row"
                        },
                        new
                        {
                            Id = 38,
                            MuscleId = 5,
                            Name = "Pull-ups"
                        },
                        new
                        {
                            Id = 39,
                            MuscleId = 5,
                            Name = "Lat pulldowns"
                        },
                        new
                        {
                            Id = 40,
                            MuscleId = 5,
                            Name = "Seated cable rows"
                        },
                        new
                        {
                            Id = 41,
                            MuscleId = 5,
                            Name = "Wide grip pull-ups"
                        },
                        new
                        {
                            Id = 42,
                            MuscleId = 5,
                            Name = "Inverted rows"
                        },
                        new
                        {
                            Id = 43,
                            MuscleId = 5,
                            Name = "Straight arm pulldowns"
                        },
                        new
                        {
                            Id = 44,
                            MuscleId = 5,
                            Name = "Single-arm dumbbell rows"
                        },
                        new
                        {
                            Id = 45,
                            MuscleId = 5,
                            Name = "Barbell Rows"
                        },
                        new
                        {
                            Id = 46,
                            MuscleId = 5,
                            Name = "Close-grip Pulldowns"
                        },
                        new
                        {
                            Id = 47,
                            MuscleId = 5,
                            Name = "Underhand Cable Pulldowns"
                        },
                        new
                        {
                            Id = 48,
                            MuscleId = 5,
                            Name = "Seated Row Machine"
                        },
                        new
                        {
                            Id = 49,
                            MuscleId = 5,
                            Name = "Wide Grip Cable Rows"
                        },
                        new
                        {
                            Id = 50,
                            MuscleId = 6,
                            Name = "Hyperextensions"
                        },
                        new
                        {
                            Id = 51,
                            MuscleId = 6,
                            Name = "Deadlifts"
                        },
                        new
                        {
                            Id = 52,
                            MuscleId = 6,
                            Name = "Good mornings"
                        },
                        new
                        {
                            Id = 53,
                            MuscleId = 6,
                            Name = "Supermans"
                        },
                        new
                        {
                            Id = 54,
                            MuscleId = 6,
                            Name = "Back extensions"
                        },
                        new
                        {
                            Id = 55,
                            MuscleId = 6,
                            Name = "Romanian deadlifts"
                        },
                        new
                        {
                            Id = 56,
                            MuscleId = 6,
                            Name = "Reverse hypers"
                        },
                        new
                        {
                            Id = 57,
                            MuscleId = 6,
                            Name = "Bird dogs"
                        },
                        new
                        {
                            Id = 58,
                            MuscleId = 6,
                            Name = "Russian twists"
                        },
                        new
                        {
                            Id = 59,
                            MuscleId = 6,
                            Name = "Plank variations"
                        },
                        new
                        {
                            Id = 60,
                            MuscleId = 6,
                            Name = "Seated Good Mornings"
                        },
                        new
                        {
                            Id = 61,
                            MuscleId = 6,
                            Name = "Prone Back Extensions"
                        },
                        new
                        {
                            Id = 62,
                            MuscleId = 6,
                            Name = "Seated Cable Hyperextensions"
                        },
                        new
                        {
                            Id = 63,
                            MuscleId = 6,
                            Name = "Kettlebell Swings"
                        },
                        new
                        {
                            Id = 64,
                            MuscleId = 6,
                            Name = "Reverse Hyper Machine"
                        },
                        new
                        {
                            Id = 65,
                            MuscleId = 7,
                            Name = "Barbell curls"
                        },
                        new
                        {
                            Id = 66,
                            MuscleId = 7,
                            Name = "Dumbbell Hammer curls"
                        },
                        new
                        {
                            Id = 67,
                            MuscleId = 7,
                            Name = "Preacher Hammer curls"
                        },
                        new
                        {
                            Id = 68,
                            MuscleId = 7,
                            Name = "Cable Hammer curls"
                        },
                        new
                        {
                            Id = 69,
                            MuscleId = 7,
                            Name = "Incline Hammer curls"
                        },
                        new
                        {
                            Id = 70,
                            MuscleId = 8,
                            Name = "Hammer curls"
                        },
                        new
                        {
                            Id = 71,
                            MuscleId = 8,
                            Name = "Reverse curls"
                        },
                        new
                        {
                            Id = 72,
                            MuscleId = 8,
                            Name = "Wrist curls"
                        },
                        new
                        {
                            Id = 73,
                            MuscleId = 8,
                            Name = "Zottman curls"
                        },
                        new
                        {
                            Id = 74,
                            MuscleId = 8,
                            Name = "EZ bar reverse curls"
                        },
                        new
                        {
                            Id = 75,
                            MuscleId = 9,
                            Name = "Dumbbell curls"
                        },
                        new
                        {
                            Id = 76,
                            MuscleId = 9,
                            Name = "Preacher curls"
                        },
                        new
                        {
                            Id = 77,
                            MuscleId = 9,
                            Name = "Concentration curls"
                        },
                        new
                        {
                            Id = 78,
                            MuscleId = 9,
                            Name = "EZ bar curls"
                        },
                        new
                        {
                            Id = 79,
                            MuscleId = 9,
                            Name = "Incline dumbbell curls"
                        },
                        new
                        {
                            Id = 80,
                            MuscleId = 9,
                            Name = "Cable curls"
                        },
                        new
                        {
                            Id = 81,
                            MuscleId = 9,
                            Name = "Spider curls"
                        },
                        new
                        {
                            Id = 82,
                            MuscleId = 9,
                            Name = "Chin-ups"
                        },
                        new
                        {
                            Id = 83,
                            MuscleId = 9,
                            Name = "Seated Dumbbell curls"
                        },
                        new
                        {
                            Id = 84,
                            MuscleId = 9,
                            Name = "Hammer Strength curls"
                        },
                        new
                        {
                            Id = 85,
                            MuscleId = 9,
                            Name = "Machine curls"
                        },
                        new
                        {
                            Id = 86,
                            MuscleId = 9,
                            Name = "Close-grip Chin-ups"
                        },
                        new
                        {
                            Id = 87,
                            MuscleId = 9,
                            Name = "Preacher Hammer curls"
                        },
                        new
                        {
                            Id = 88,
                            MuscleId = 10,
                            Name = "Close grip bench press"
                        },
                        new
                        {
                            Id = 89,
                            MuscleId = 10,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 90,
                            MuscleId = 10,
                            Name = "Diamond push-ups"
                        },
                        new
                        {
                            Id = 91,
                            MuscleId = 10,
                            Name = "Overhead dumbbell extension"
                        },
                        new
                        {
                            Id = 92,
                            MuscleId = 10,
                            Name = "Reverse grip triceps pushdown"
                        },
                        new
                        {
                            Id = 93,
                            MuscleId = 11,
                            Name = "Triceps pushdown"
                        },
                        new
                        {
                            Id = 94,
                            MuscleId = 11,
                            Name = "Triceps kickbacks"
                        },
                        new
                        {
                            Id = 95,
                            MuscleId = 11,
                            Name = "Triceps rope pushdown"
                        },
                        new
                        {
                            Id = 96,
                            MuscleId = 11,
                            Name = "Close grip push-ups"
                        },
                        new
                        {
                            Id = 97,
                            MuscleId = 11,
                            Name = "Bench dips"
                        },
                        new
                        {
                            Id = 98,
                            MuscleId = 12,
                            Name = "Overhead triceps extension"
                        },
                        new
                        {
                            Id = 99,
                            MuscleId = 12,
                            Name = "Skull crushers"
                        },
                        new
                        {
                            Id = 100,
                            MuscleId = 12,
                            Name = "Bench dips"
                        },
                        new
                        {
                            Id = 101,
                            MuscleId = 12,
                            Name = "Overhead cable triceps extension"
                        },
                        new
                        {
                            Id = 102,
                            MuscleId = 12,
                            Name = "Dumbbell triceps kickbacks"
                        },
                        new
                        {
                            Id = 103,
                            MuscleId = 13,
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 104,
                            MuscleId = 13,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 105,
                            MuscleId = 13,
                            Name = "Sit-ups"
                        },
                        new
                        {
                            Id = 106,
                            MuscleId = 13,
                            Name = "Mountain climbers"
                        },
                        new
                        {
                            Id = 107,
                            MuscleId = 13,
                            Name = "Ab wheel rollouts"
                        },
                        new
                        {
                            Id = 108,
                            MuscleId = 14,
                            Name = "Leg raises"
                        },
                        new
                        {
                            Id = 109,
                            MuscleId = 14,
                            Name = "Hanging knee raises"
                        },
                        new
                        {
                            Id = 110,
                            MuscleId = 14,
                            Name = "Reverse crunches"
                        },
                        new
                        {
                            Id = 111,
                            MuscleId = 14,
                            Name = "Scissor kicks"
                        },
                        new
                        {
                            Id = 112,
                            MuscleId = 14,
                            Name = "Captain's chair leg raises"
                        },
                        new
                        {
                            Id = 113,
                            MuscleId = 15,
                            Name = "Russian twists"
                        },
                        new
                        {
                            Id = 114,
                            MuscleId = 15,
                            Name = "Side plank"
                        },
                        new
                        {
                            Id = 115,
                            MuscleId = 15,
                            Name = "Bicycle crunches"
                        },
                        new
                        {
                            Id = 116,
                            MuscleId = 15,
                            Name = "Woodchoppers"
                        },
                        new
                        {
                            Id = 117,
                            MuscleId = 15,
                            Name = "Standing oblique crunches"
                        },
                        new
                        {
                            Id = 118,
                            MuscleId = 16,
                            Name = "Standing calf raises"
                        },
                        new
                        {
                            Id = 119,
                            MuscleId = 16,
                            Name = "Donkey calf raises"
                        },
                        new
                        {
                            Id = 120,
                            MuscleId = 16,
                            Name = "Calf press on leg press machine"
                        },
                        new
                        {
                            Id = 121,
                            MuscleId = 16,
                            Name = "Skipping rope"
                        },
                        new
                        {
                            Id = 122,
                            MuscleId = 16,
                            Name = "Jump rope calf jumps"
                        },
                        new
                        {
                            Id = 123,
                            MuscleId = 17,
                            Name = "Seated calf raises"
                        },
                        new
                        {
                            Id = 124,
                            MuscleId = 17,
                            Name = "Single-leg calf raises"
                        },
                        new
                        {
                            Id = 125,
                            MuscleId = 17,
                            Name = "Calf raises on a step"
                        },
                        new
                        {
                            Id = 126,
                            MuscleId = 17,
                            Name = "Sled pushes"
                        },
                        new
                        {
                            Id = 127,
                            MuscleId = 17,
                            Name = "Calf raises with resistance bands"
                        },
                        new
                        {
                            Id = 128,
                            MuscleId = 18,
                            Name = "Toe raises"
                        },
                        new
                        {
                            Id = 129,
                            MuscleId = 18,
                            Name = "Box jumps"
                        },
                        new
                        {
                            Id = 130,
                            MuscleId = 18,
                            Name = "Ankle dorsiflexion with resistance band"
                        },
                        new
                        {
                            Id = 131,
                            MuscleId = 18,
                            Name = "Treadmill incline walks"
                        },
                        new
                        {
                            Id = 132,
                            MuscleId = 19,
                            Name = "Squats"
                        },
                        new
                        {
                            Id = 133,
                            MuscleId = 19,
                            Name = "Step-ups"
                        },
                        new
                        {
                            Id = 134,
                            MuscleId = 19,
                            Name = "Front squats"
                        },
                        new
                        {
                            Id = 135,
                            MuscleId = 19,
                            Name = "Wall sits"
                        },
                        new
                        {
                            Id = 136,
                            MuscleId = 19,
                            Name = "Leg press"
                        },
                        new
                        {
                            Id = 137,
                            MuscleId = 20,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 138,
                            MuscleId = 20,
                            Name = "Hack squats"
                        },
                        new
                        {
                            Id = 139,
                            MuscleId = 20,
                            Name = "Leg extensions"
                        },
                        new
                        {
                            Id = 140,
                            MuscleId = 20,
                            Name = "Leg press"
                        },
                        new
                        {
                            Id = 141,
                            MuscleId = 20,
                            Name = "Leg press with feet high"
                        },
                        new
                        {
                            Id = 142,
                            MuscleId = 21,
                            Name = "Leg press"
                        },
                        new
                        {
                            Id = 143,
                            MuscleId = 21,
                            Name = "Bulgarian split squats"
                        },
                        new
                        {
                            Id = 144,
                            MuscleId = 21,
                            Name = "Pistol squats"
                        },
                        new
                        {
                            Id = 145,
                            MuscleId = 21,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 146,
                            MuscleId = 21,
                            Name = "Leg extensions"
                        },
                        new
                        {
                            Id = 147,
                            MuscleId = 22,
                            Name = "Hip thrusts"
                        },
                        new
                        {
                            Id = 148,
                            MuscleId = 22,
                            Name = "Donkey kicks"
                        },
                        new
                        {
                            Id = 149,
                            MuscleId = 22,
                            Name = "Sumo squats"
                        },
                        new
                        {
                            Id = 150,
                            MuscleId = 22,
                            Name = "Kickbacks"
                        },
                        new
                        {
                            Id = 151,
                            MuscleId = 22,
                            Name = "Bulgarian split squats"
                        },
                        new
                        {
                            Id = 152,
                            MuscleId = 23,
                            Name = "Clamshell exercises"
                        },
                        new
                        {
                            Id = 153,
                            MuscleId = 23,
                            Name = "Fire hydrants"
                        },
                        new
                        {
                            Id = 154,
                            MuscleId = 23,
                            Name = "Side-lying leg lifts"
                        },
                        new
                        {
                            Id = 155,
                            MuscleId = 23,
                            Name = "Lateral band walks"
                        },
                        new
                        {
                            Id = 156,
                            MuscleId = 24,
                            Name = "Glute bridges"
                        },
                        new
                        {
                            Id = 157,
                            MuscleId = 24,
                            Name = "Single-leg hip thrusts"
                        },
                        new
                        {
                            Id = 158,
                            MuscleId = 24,
                            Name = "Banded crab walks"
                        },
                        new
                        {
                            Id = 159,
                            MuscleId = 24,
                            Name = "Reverse lunges"
                        },
                        new
                        {
                            Id = 160,
                            MuscleId = 25,
                            Name = "Wrist curls"
                        },
                        new
                        {
                            Id = 161,
                            MuscleId = 25,
                            Name = "Plate curls"
                        },
                        new
                        {
                            Id = 162,
                            MuscleId = 25,
                            Name = "Pinch grip holds"
                        },
                        new
                        {
                            Id = 163,
                            MuscleId = 25,
                            Name = "Finger curls"
                        },
                        new
                        {
                            Id = 164,
                            MuscleId = 25,
                            Name = "Dumbbell wrist pronation/supination"
                        },
                        new
                        {
                            Id = 165,
                            MuscleId = 26,
                            Name = "Reverse wrist curls"
                        },
                        new
                        {
                            Id = 166,
                            MuscleId = 26,
                            Name = "Hammer grip curls"
                        },
                        new
                        {
                            Id = 167,
                            MuscleId = 26,
                            Name = "Bar hangs"
                        },
                        new
                        {
                            Id = 168,
                            MuscleId = 26,
                            Name = "Wrist roller"
                        },
                        new
                        {
                            Id = 169,
                            MuscleId = 27,
                            Name = "Grip strengthener exercises"
                        },
                        new
                        {
                            Id = 170,
                            MuscleId = 27,
                            Name = "Towel hangs"
                        },
                        new
                        {
                            Id = 171,
                            MuscleId = 27,
                            Name = "Farmer's walks"
                        },
                        new
                        {
                            Id = 172,
                            MuscleId = 27,
                            Name = "Plate pinches"
                        });
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MainMuscle")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Muscles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainMuscle = 0,
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 2,
                            MainMuscle = 0,
                            Name = "Middle Chest"
                        },
                        new
                        {
                            Id = 3,
                            MainMuscle = 0,
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 4,
                            MainMuscle = 1,
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 5,
                            MainMuscle = 1,
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 6,
                            MainMuscle = 1,
                            Name = "Low Back"
                        },
                        new
                        {
                            Id = 7,
                            MainMuscle = 2,
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 8,
                            MainMuscle = 2,
                            Name = "Brachioradialis"
                        },
                        new
                        {
                            Id = 9,
                            MainMuscle = 2,
                            Name = "Biceps Brachii"
                        },
                        new
                        {
                            Id = 10,
                            MainMuscle = 3,
                            Name = "Long Head of Triceps"
                        },
                        new
                        {
                            Id = 11,
                            MainMuscle = 3,
                            Name = "Medial Head of Triceps"
                        },
                        new
                        {
                            Id = 12,
                            MainMuscle = 3,
                            Name = "Lateral Head of Triceps"
                        },
                        new
                        {
                            Id = 13,
                            MainMuscle = 4,
                            Name = "Upper Abs"
                        },
                        new
                        {
                            Id = 14,
                            MainMuscle = 4,
                            Name = "Lower Abs"
                        },
                        new
                        {
                            Id = 15,
                            MainMuscle = 4,
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 16,
                            MainMuscle = 5,
                            Name = "Gastrocnemius (Upper Calf)"
                        },
                        new
                        {
                            Id = 17,
                            MainMuscle = 5,
                            Name = "Soleus (Lower Calf)"
                        },
                        new
                        {
                            Id = 18,
                            MainMuscle = 5,
                            Name = "Tibialis Anterior"
                        },
                        new
                        {
                            Id = 19,
                            MainMuscle = 6,
                            Name = "Vastus Lateralis"
                        },
                        new
                        {
                            Id = 20,
                            MainMuscle = 6,
                            Name = "Vastus Medialis"
                        },
                        new
                        {
                            Id = 21,
                            MainMuscle = 6,
                            Name = "Rectus Femoris"
                        },
                        new
                        {
                            Id = 22,
                            MainMuscle = 7,
                            Name = "Gluteus Maximus"
                        },
                        new
                        {
                            Id = 23,
                            MainMuscle = 7,
                            Name = "Gluteus Medius"
                        },
                        new
                        {
                            Id = 24,
                            MainMuscle = 7,
                            Name = "Gluteus Minimus"
                        },
                        new
                        {
                            Id = 25,
                            MainMuscle = 8,
                            Name = "Wrist Flexors"
                        },
                        new
                        {
                            Id = 26,
                            MainMuscle = 8,
                            Name = "Wrist Extensors"
                        },
                        new
                        {
                            Id = 27,
                            MainMuscle = 8,
                            Name = "Grip"
                        });
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("CFKA.Health.Domain.Entities.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("CFKA.Health.Domain.Entities.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
